stages:
  get_data:
    cmd: PYTHONPATH=. python src/data/get_data.py
    outs:
      - data/raw/train.txt
      - data/raw/test.txt
      - data/raw/val.txt

  preprocess:
    cmd: PYTHONPATH=. python src/data/data_preprocessing.py
    deps:
      - data/raw/train.txt
      - data/raw/test.txt
      - data/raw/val.txt
    outs:
      - data/preprocessed/preprocessed_x_train.joblib
      - data/preprocessed/preprocessed_y_train.joblib
      - data/preprocessed/preprocessed_x_test.joblib
      - data/preprocessed/preprocessed_y_test.joblib
      - data/preprocessed/preprocessed_x_val.joblib
      - data/preprocessed/preprocessed_y_val.joblib
      - data/preprocessed/char_index.joblib

  define_model:
    cmd: PYTHONPATH=. python src/models/define_model.py
    deps:
      - data/preprocessed/char_index.joblib
    outs:
      - models/defined_model.joblib

  train_model:
    cmd: PYTHONPATH=. python src/models/train_model.py
    deps:
      - models/defined_model.joblib
      - data/preprocessed/preprocessed_x_train.joblib
      - data/preprocessed/preprocessed_y_train.joblib
      - data/preprocessed/preprocessed_x_val.joblib
      - data/preprocessed/preprocessed_y_val.joblib
    outs:
      - models/trained_model.joblib

  evaluate_model:
    cmd: PYTHONPATH=. python src/models/evaluate_model.py
    deps:
      - models/trained_model.joblib
      - data/preprocessed/preprocessed_x_test.joblib
      - data/preprocessed/preprocessed_y_test.joblib
    outs:
      - evaluation/metrics.json
      - evaluation/plots/roc.json
      - evaluation/plots/prc.json
      - evaluation/plots/cm.json

plots:
  - ROC:
      template: simple
      x: fpr
      y:
        evaluation/plots/roc.json: tpr
  - Precision-Recall:
      template: simple
      x: recall
      y:
        evaluation/plots/prc.json: precision
  - Confusion-Matrix:
      template: confusion
      x: actual
      y: predicted
