name: Tests

on:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Load Poetry cache
      id: load-poetry-cache
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.load-poetry-cache.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Set up DVC remote with AWS credentials
      run: |
        source .venv/bin/activate
        dvc remote modify aws_s3 access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify aws_s3 secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest tests

    - name: Extract metrics and update README
      run: |
        metrics=$(cat evaluation/metrics.json | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]')
        for metric in $metrics; do
          key=$(echo $metric | cut -d'=' -f1)
          value=$(echo $metric | cut -d'=' -f2)
          badge_url="https://img.shields.io/badge/${key}-${value}-blue"
          # Update or add the badge in the README
          if grep -q "![${key}]" README.md; then
            sed -i 's|!\[${key}\](.*)|![${key}](${badge_url})|' README.md
          else
            echo "![${key}](${badge_url})" >> README.md
          fi
        done
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m 'Update README with test metrics badges'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}